[package]
name = "are_we_web_yet"
version = "0.2.0"
authors = ["Mark Oleson <fusion2004@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
diesel = { version = "1.4", features = ["postgres"] }
dotenv = "0.13.0"
env_logger = "0.6"
gotham = "0.3"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
