[package]
name = "are_we_web_yet"
version = "0.2.0"
authors = ["Mark Oleson <fusion2004@gmail.com>"]

[dependencies]
clap = "2"
diesel = { version = "1.4", features = ["postgres"] }
dotenv = "0.13.0"
gotham = "0.3"
serde = "1.0"
serde_json = "1.0"
